export const ROUTE_HOME = 'ROUTE_HOME'

export const ROUTE_AIRDROP_CREATE = 'ROUTE_AIRDROP_CREATE'
export const ROUTE_AIRDROP_SUMMARY = 'ROUTE_AIRDROP_SUMMARY'
export const ROUTE_AIRDROP_DROP = 'ROUTE_AIRDROP_DROP'

export const ROUTE_ERROR_404 = 'ROUTE_ERROR_404'
